name: with job dependency

on:
  push:
    branches:
      - main
jobs:
  build2:
    name: build2
    runs-on: ubuntu-latest
    steps:
      - run: echo build

  test2:
    name: test2
    runs-on: ubuntu-latest
    needs: [build2]
    steps:
      - run: echo hello

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: echo lint
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [lint, test2]
    steps:
      - uses: actions/checkout@v2
      - run: echo deploy
