name: with job dependency

on: push

jobs:
  build2:
    name: build2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo build

  test2:
    name: test2
    runs-on: ubuntu-latest
    needs: [build2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo hello world
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo lint
