name: with job dependency

on:
  push:
    branches:
      - main
jobs:
  build2:
    name: build2
    runs-on: ubuntu-latest
    steps:
      - run: echo build

  test2:
    name: test2
    runs-on: ubuntu-latest
    needs: [build2]
    steps:
      - run: echo hello

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: echo lint
  
  deploy_test:
    name: deploy_test
    runs-on: ubuntu-latest
    needs: [lint, test2]
    steps:
      - uses: actions/checkout@v2
      - run: echo deploy ${{ secrets.MY_SECRET }}
    environment:
      name: test-env
      url: https://arizuk.github.io/

  # environment以外共有するやり方はありそう
  deploy_prod:
    name: deploy_prod
    runs-on: ubuntu-latest
    needs: [lint, test2]
    steps:
      - uses: actions/checkout@v2
      - run: echo deploy ${{ secrets.MY_SECRET }}
    environment:
      name: prod-env
      url: https://arizuk.github.io/
