name: on_pullrequest
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ toJSON(github.event.pull_request.head.milestone) }}'